%Import data and designate
openai = readtable("openai.xlsx");

human_ann = cell2mat(table2cell(openai(:,8)));
array_team = cell2mat(table2cell(openai(:,4:7)));
prompt = table2array(openai(:,1));
human_ans = table2array(openai(:,2));
llm_ans = table2array(openai(:,3));
feedback = table2array(openai(:,9));

% Define the data
data_openai = struct(...
    'llm_name', 'open_ai/gpt-4', ...
    'category', 'free-form-text', ...
    'task_prompt', sprintf("{'role': 'system', 'content': 'What is the answer to this joke?'}, {'role': 'user', 'content': 'What did the janitor say when he jumped out of the closet?'},{'role': 'assistant', 'content': 'Supplies!'},{'role': 'user','content': %s}",...
    'prompt'), ...
    'prompting_setup', 'few-shot', ...
    'no_of_example', 1, ...
    'generated_response', 'llm_ans', ...
    'final_annotation', 'human_ann', ...
    'individual_annotations', 'array_team', ...
    'real_response', 'human_ans', ...
    'llm_setting', struct(...
        'engine', 'gpt-4', ...
        'temperature', 1.0, ...
        'max_tokens', 128, ...
        'n', 1, ...
        'top_p', 1, ...
        'stream', 'False', ...
        'stop', 'None', ...
        'frequency_penalty', 0, ...
        'presence_penalty', 0), ...
    'feedback', 'feedback');



for i=1:100
    data_openai(i) = struct(...
    'llm_name', 'open_ai/gpt-4', ...
    'category', 'free-form-text', ...
    'task_prompt', sprintf("{'role': 'system', 'content': 'What is the answer to this joke?'}, {'role': 'user', 'content': 'What did the janitor say when he jumped out of the closet?'},{'role': 'assistant', 'content': 'Supplies!'},{'role': 'user','content': %s}",...
    prompt{i}), ...
    'prompting_setup', 'few-shot', ...
    'no_of_example', 1, ...
    'generated_response', llm_ans{i}, ...
    'real_response', human_ans{i}, ...
    'final_annotation', human_ann(i), ...
    'individual_annotations', array_team(i,:), ...
    'llm_setting', struct(...
        'engine', 'gpt-4', ...
        'temperature', 1.0, ...
        'max_tokens', 128, ...
        'n', 1, ...
        'top_p', 1, ...
        'stream', 'False', ...
        'stop', 'None', ...
        'frequency_penalty', 0, ...
        'presence_penalty', 0, ...
        'logit_bias', {}), ...
    'feedback', feedback{i});      
end
% Convert the data to JSON format
json_openai = jsonencode(data_openai);
